### Добавление нового пользователя
POST http://localhost:8080/exchange/user
Content-Type: application/json

{
  "username": "Dmitrii",
  "email": "dmitrii@yandex.ru"
}

### Вывод всех пользователей
GET http://localhost:8080/exchange/user/all