###Запрос данных кошелька
GET http://localhost:8080/exchange/wallet/balance?key=YHs`g:vJZX0mQonw]4dBt[Zlr

###Запрос баланса всех кошельков по определенной валюте (админ)
GET http://localhost:8080/exchange/wallet/currency-balance?secret_key=vcT6@Nwr7eQu<d@?50GHLEIAu&currency=BTC

###Добавление валюты в кошелек
POST http://localhost:8080/exchange/wallet/add?secret_key=YHs`g:vJZX0mQonw]4dBt[Zlr&RUB=1000&TON=7&BTC=0.1

###Вывод средств
POST http://localhost:8080/exchange/wallet/withdrawal-of-funds?secret_key=YHs`g:vJZX0mQonw]4dBt[Zlr&currency=TON&count=7832&credit_card=1234 5678 9012 3456

###Обмен валют
POST http://localhost:8080/exchange/wallet/transaction?secret_key=YHs`g:vJZX0mQonw]4dBt[Zlr&currency_from=BTC&currency_to=TON&amount=12